server:
  addr: ":5001"

token:
  issuer: "Registry auth server"  # Must match issuer in the Registry config.
  expiration: 900
  certificate: "/config/server.pem"
  key: "/config/server.key"

users:
  # Password is specified as a BCrypt hash. Use `htpasswd -nB USERNAME` to generate.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin

acl:
  - match: {account: "admin"}
    actions: ["*"]
    comment: "Admin has full access to everything."
